security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: front_page
                enable_csrf: true
            logout:
                path: logout
                target: front_page

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
