services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8091:80"
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://app:app@db:5432/app?serverVersion=16&charset=utf8"
      VAULT_PATH: /var/vault/repo
    volumes:
      - ./:/app
      - vault_data:/var/vault
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  vault_data:
