<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260820110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'OAuth dynamic client registration table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE oauth_dynamic_clients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id VARCHAR(64) NOT NULL, redirect_uris JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_OAUTH_DCR_CLIENT ON oauth_dynamic_clients (client_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE oauth_dynamic_clients');
    }
}
