<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260816200300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Phase 3: session note drafts, share tokens, note published_at';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE notes ADD published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE TABLE session_note_drafts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_id INT NOT NULL, title VARCHAR(255) NOT NULL, session_date DATE NOT NULL, body TEXT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DRAFT_AUTHOR ON session_note_drafts (author_id)');
        $this->addSql('CREATE TABLE share_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note_id INT NOT NULL, token VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SHARE_TOKEN ON share_tokens (token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SHARE_NOTE ON share_tokens (note_id)');
        $this->addSql('ALTER TABLE session_note_drafts ADD CONSTRAINT FK_DRAFT_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE share_tokens ADD CONSTRAINT FK_SHARE_NOTE FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE session_note_drafts DROP CONSTRAINT FK_DRAFT_AUTHOR');
        $this->addSql('ALTER TABLE share_tokens DROP CONSTRAINT FK_SHARE_NOTE');
        $this->addSql('DROP TABLE session_note_drafts');
        $this->addSql('DROP TABLE share_tokens');
        $this->addSql('ALTER TABLE notes DROP published_at');
    }
}
