<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260816165133 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE hidden_paths (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(1024) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_545352CFB548B0F ON hidden_paths (path)');
        $this->addSql("INSERT INTO hidden_paths (path) VALUES ('A - GM')");
        $this->addSql("INSERT INTO hidden_paths (path) VALUES ('Home.md')");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE hidden_paths');
    }
}
