<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260816210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Phase 4: note markdown for MCP, search vector, user API tokens';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE notes ADD body_markdown TEXT NOT NULL DEFAULT \'\'');
        $this->addSql('ALTER TABLE notes ADD wikilinks JSON NOT NULL DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE notes ADD search_vector tsvector');
        $this->addSql('CREATE INDEX notes_search_idx ON notes USING GIN(search_vector)');
        $this->addSql('CREATE TABLE user_api_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, token_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_API_TOKEN_USER ON user_api_tokens (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_API_TOKEN_HASH ON user_api_tokens (token_hash)');
        $this->addSql('ALTER TABLE user_api_tokens ADD CONSTRAINT FK_API_TOKEN_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_api_tokens DROP CONSTRAINT FK_API_TOKEN_USER');
        $this->addSql('DROP TABLE user_api_tokens');
        $this->addSql('DROP INDEX notes_search_idx');
        $this->addSql('ALTER TABLE notes DROP search_vector');
        $this->addSql('ALTER TABLE notes DROP wikilinks');
        $this->addSql('ALTER TABLE notes DROP body_markdown');
    }
}
