<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260815063238 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, vault_path VARCHAR(1024) NOT NULL, slug VARCHAR(1024) NOT NULL, title VARCHAR(255) NOT NULL, top_level_folder VARCHAR(255) NOT NULL, html TEXT NOT NULL, report_number INT DEFAULT NULL, session_date DATE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11BA68CFB83F2F5 ON notes (vault_path)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11BA68C989D9B62 ON notes (slug)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE notes');
    }
}
