<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260820100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Claude MCP OAuth: client, authorization code, access token, refresh token tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_oauth_clients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, client_id VARCHAR(64) NOT NULL, client_secret_hash VARCHAR(64) NOT NULL, redirect_uris JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_OAUTH_CLIENT_USER ON user_oauth_clients (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_OAUTH_CLIENT_ID ON user_oauth_clients (client_id)');
        $this->addSql('ALTER TABLE user_oauth_clients ADD CONSTRAINT FK_OAUTH_CLIENT_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE oauth_authorization_codes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_hash VARCHAR(64) NOT NULL, client_id VARCHAR(64) NOT NULL, user_id INT NOT NULL, redirect_uri VARCHAR(2048) NOT NULL, code_challenge VARCHAR(128) NOT NULL, resource VARCHAR(2048) DEFAULT NULL, scope VARCHAR(255) NOT NULL DEFAULT \'mcp:read\', expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_OAUTH_AUTH_CODE_HASH ON oauth_authorization_codes (code_hash)');
        $this->addSql('ALTER TABLE oauth_authorization_codes ADD CONSTRAINT FK_OAUTH_AUTH_CODE_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE oauth_access_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, user_id INT NOT NULL, client_id VARCHAR(64) NOT NULL, scope VARCHAR(255) NOT NULL DEFAULT \'mcp:read\', expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_OAUTH_ACCESS_TOKEN_HASH ON oauth_access_tokens (token_hash)');
        $this->addSql('ALTER TABLE oauth_access_tokens ADD CONSTRAINT FK_OAUTH_ACCESS_TOKEN_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE oauth_refresh_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, user_id INT NOT NULL, client_id VARCHAR(64) NOT NULL, access_token_id INT NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_OAUTH_REFRESH_TOKEN_HASH ON oauth_refresh_tokens (token_hash)');
        $this->addSql('ALTER TABLE oauth_refresh_tokens ADD CONSTRAINT FK_OAUTH_REFRESH_TOKEN_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth_refresh_tokens ADD CONSTRAINT FK_OAUTH_REFRESH_TOKEN_ACCESS FOREIGN KEY (access_token_id) REFERENCES oauth_access_tokens (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE oauth_refresh_tokens DROP CONSTRAINT FK_OAUTH_REFRESH_TOKEN_ACCESS');
        $this->addSql('ALTER TABLE oauth_refresh_tokens DROP CONSTRAINT FK_OAUTH_REFRESH_TOKEN_USER');
        $this->addSql('DROP TABLE oauth_refresh_tokens');
        $this->addSql('ALTER TABLE oauth_access_tokens DROP CONSTRAINT FK_OAUTH_ACCESS_TOKEN_USER');
        $this->addSql('DROP TABLE oauth_access_tokens');
        $this->addSql('ALTER TABLE oauth_authorization_codes DROP CONSTRAINT FK_OAUTH_AUTH_CODE_USER');
        $this->addSql('DROP TABLE oauth_authorization_codes');
        $this->addSql('ALTER TABLE user_oauth_clients DROP CONSTRAINT FK_OAUTH_CLIENT_USER');
        $this->addSql('DROP TABLE user_oauth_clients');
    }
}
